---
- name: Import grafana
  group:
    name: grafana
    gid: 472
    
- name: Grafana directory
  file:
    name: /opt/docker/grafana
    state: directory
    owner: "472"
    group: "472"
    recurse: true

- name: Grafana container
  docker_container:
    name: grafana
    image: grafana/grafana
    env:
      GF_SERVER_ROOT_URL: "http://localhost:{{ docker_grafana_port }}/grafana"
      GF_SERVER_SERVE_FROM_SUB_PATH: "true"
    volumes:
      - /opt/docker/grafana:/var/lib/grafana
    ports:
      - "{{ docker_grafana_port }}:{{ grafana_port }}"
    restart_policy: always